"""
Lightweight single-file agent framework.
"""

from __future__ import annotations

from bos.protocol import Envelope, TurnEvent

from ._utils import (
    _aclose,
    _allowed,
    _apply,
    _apply_async,
    _as_parts,
    _build_params,
    _compact,
    _create_extension_instance,
    _flock,
    _get_bos_home,
    _litellm_response_to_llm_response,
    _litellm_tool_calls_to_requests,
    _load_ext_modules,
    _load_ext_paths,
    _load_json,
    _pick_collection,
    _read_text,
    _safe_format,
    _strip_think,
)
from .actor import AgentActor
from .agent import AbortTurn, ChainReactInterceptor, ReactAgent, TurnContext
from .contract import (
    Agent,
    Channel,
    Closeable,
    Consolidator,
    EventSink,
    MailBox,
    MailRoute,
    MemoryEntry,
    MemoryExtension,
    Message,
    MessageStore,
    SkillsLoader,
    TurnInterceptor,
    ep_actor_command,
    ep_agent,
    ep_channel,
    ep_consolidator,
    ep_mail_route,
    ep_memory,
    ep_message_store,
    ep_provider,
    ep_skills_loader,
    ep_tool,
    ep_turn_interceptor,
)
from .harness import (
    CURRENT_HARNESS,
    CURRENT_MAILBOX,
    AgentHarness,
    bootstrap_platform,
)
from .llm import LLMClient, LLMResponse, ToolCallRequest
from .registry import Extension, ExtensionPoint, ToolRegistry

__all__ = [
    "AbortTurn",
    "Agent",
    "AgentActor",
    "AgentHarness",
    "CURRENT_HARNESS",
    "CURRENT_MAILBOX",
    "Channel",
    "ChainReactInterceptor",
    "Closeable",
    "Consolidator",
    "Envelope",
    "EventSink",
    "Extension",
    "ExtensionPoint",
    "LLMClient",
    "LLMResponse",
    "MailBox",
    "MailRoute",
    "MemoryEntry",
    "MemoryExtension",
    "Message",
    "MessageStore",
    "ReactAgent",
    "SkillsLoader",
    "ToolCallRequest",
    "ToolRegistry",
    "TurnContext",
    "TurnInterceptor",
    "TurnEvent",
    "bootstrap_platform",
    "ep_actor_command",
    "ep_agent",
    "ep_channel",
    "ep_consolidator",
    "ep_mail_route",
    "ep_memory",
    "ep_message_store",
    "ep_provider",
    "ep_skills_loader",
    "ep_tool",
    "ep_turn_interceptor",
    "_aclose",
    "_allowed",
    "_apply",
    "_apply_async",
    "_as_parts",
    "_build_params",
    "_compact",
    "_create_extension_instance",
    "_flock",
    "_litellm_response_to_llm_response",
    "_litellm_tool_calls_to_requests",
    "_load_ext_modules",
    "_load_ext_paths",
    "_load_json",
    "_pick_collection",
    "_read_text",
    "_safe_format",
    "_strip_think",
    "_get_bos_home",
]
