"""
Lightweight single-file agent framework.
"""

from __future__ import annotations

from bos.protocol import Envelope

from ._utils import (
    _aclose,
    _allowed,
    _apply,
    _apply_async,
    _as_parts,
    _build_params,
    _compact,
    _create_extension_instance,
    _flock,
    _litellm_response_to_llm_response,
    _litellm_tool_calls_to_requests,
    _load_ext_modules,
    _load_ext_paths,
    _load_json,
    _pick_collection,
    _read_text,
    _safe_format,
    _strip_think,
)
from .actor import AgentActor
from .agent import AbortTurn, ChainReactInterceptor, ReactAgent, ReactContext
from .contract import (
    Agent,
    Channel,
    Closeable,
    Consolidator,
    MailBox,
    Mailbox,
    MailRoute,
    MemoryStore,
    Message,
    MessageStore,
    ReactInterceptor,
    SkillsLoader,
    ep_actor_command,
    ep_agent,
    ep_channel,
    ep_consolidator,
    ep_mail_route,
    ep_mailbox,
    ep_memory_store,
    ep_message_store,
    ep_provider,
    ep_react_interceptor,
    ep_skills_loader,
    ep_tool,
)
from .defaults import (
    FileSystemSkillsLoader,
    InMemMailbox,
    InMemMailRoute,
    InMemMemoryStore,
    InMemMessageStore,
    NaiveConsolidator,
    litellm_complete,
)
from .harness import (
    CURRENT_HARNESS,
    AgentHarness,
    bootstrap_platform,
)
from .llm import LLMClient, LLMResponse, ToolCallRequest
from .registry import Extension, ExtensionPoint, ToolRegistry

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "AbortTurn",
    "Agent",
    "AgentActor",
    "AgentHarness",
    "CURRENT_HARNESS",
    "Channel",
    "ChainReactInterceptor",
    "Closeable",
    "Consolidator",
    "Envelope",
    "Extension",
    "ExtensionPoint",
    "FileSystemSkillsLoader",
    "InMemMailRoute",
    "InMemMailbox",
    "InMemMemoryStore",
    "InMemMessageStore",
    "LLMClient",
    "LLMResponse",
    "MailBox",
    "Mailbox",
    "MailRoute",
    "MemoryStore",
    "Message",
    "MessageStore",
    "NaiveConsolidator",
    "ReactAgent",
    "ReactContext",
    "ReactInterceptor",
    "SkillsLoader",
    "ToolCallRequest",
    "ToolRegistry",
    "bootstrap_platform",
    "ep_actor_command",
    "ep_agent",
    "ep_channel",
    "ep_consolidator",
    "ep_mail_route",
    "ep_mailbox",
    "ep_memory_store",
    "ep_message_store",
    "ep_provider",
    "ep_react_interceptor",
    "ep_skills_loader",
    "ep_tool",
    "litellm_complete",
    "_aclose",
    "_allowed",
    "_apply",
    "_apply_async",
    "_as_parts",
    "_build_params",
    "_compact",
    "_create_extension_instance",
    "_flock",
    "_litellm_response_to_llm_response",
    "_litellm_tool_calls_to_requests",
    "_load_ext_modules",
    "_load_ext_paths",
    "_load_json",
    "_pick_collection",
    "_read_text",
    "_safe_format",
    "_strip_think",
]
